import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Arika_L } from "../src/Arika_L.mjs";
import { Arika_I } from "../src/Arika_I.mjs";

let prep1 = `
    ..........
    ..........
    ..........
    ..........
    ..........
    XXXX.XXXXX`;

    let prep2 = `
    ..........
    ..........
    ..........
    ..........
    XXXX.XXXXX
    XXXX.XXXXX`;

    let prep3 = `
    ..........
    ..........
    XXXX.XXXXX
    XXXX.XXX.X
    XXXX.XXXXX
    XXXX.XXXXX`;

describe("Clearing lines", () => {
    let board;
    beforeEach(() => {
        board = new Board(10, 6);
    });

    it("One line", () => {
        board.init(prep1);
        board.drop(new Arika_L());
        board.rotate(1);
        board.fall();

        expect(board.toString()).to.equalShape(
        `..........
         ..........
         ..........
         ..........
         ...LL.....
         ....L.....`
        );
    });

    it("Multiple lines", () => {
        board.init(prep3);
        board.drop(new Arika_I());
        board.rotate(1);
        board.fall();

        expect(board.toString()).to.equalShape(
        `..........
         ..........
         ..........
         ..........
         ..........
         XXXXIXXX.X`
        );
    });

});